version: "3"

services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    container_name: playful-try-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: mysql:8.0
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    volumes:
      - data-volume:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    command: mysqld --character-set-server=utf8mb4  --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    
  migration:
    image: flyway/flyway
    depends_on:
      - db
    container_name: playful-try-migration
    volumes:
      - ./database/migration/schema:/flyway/sql

  api:
    build:
      context: ./backend
    command: reflex -r '\.go$$' -s -- sh -c 'go run cmd/api/main.go -databaseDatasource="${DATABASE_DATASOURCE}" -port=10001'
    container_name: playful-try-api
    ports:
      - 10001:10001
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
    build:
      context: ./frontend
    command: npm run dev
    container_name: playful-try-front
    ports:
      - 3000:3000
    environment:
      - BACKEND_API_BASE=http://localhost:1991
    volumes:
      - ./frontend:/app
    working_dir: /app

volumes:
  data-volume:
  careler_node_modules-volume:
